export const skills = [
    { id: 43, skillname: "MongoDB", imageUrl: "/skills/mongoDB.svg" },
    { id: 35, skillname: "Express JS", imageUrl: "/skills/expressjs.png" },
    { id: 57, skillname: "React JS", imageUrl: "/skills/react.svg" },
    { id: 8, skillname : "Node", imageUrl: "/skills/nodejs.png" },
    { id: 34, skillname: "JavaScript", imageUrl: "/skills/javascript.svg" },
    { id: 13, skillname: "C++", imageUrl: "/skills/cplusplus.svg" },
    { id: 64, skillname: "Tailwind Css", imageUrl: "/skills/tailwind.svg" },
    { id: 66, skillname: "TypeScript", imageUrl: "/skills/typescript.svg" },
    { id: 15, skillname: "CSS", imageUrl: "/skills/css.svg" },
    { id: 3, skillname : "Angular", imageUrl: "/skills/angular.svg" },
    { id: 39, skillname: "Material UI", imageUrl: "/skills/materialui.svg" },
    { id: 30, skillname: "HTML", imageUrl: "/skills/html.svg" },
    { id: 4, skillname : "AWS", imageUrl: "/skills/aws.svg" },
    { id: 5, skillname : "Azure", imageUrl: "/skills/azure.svg" },
    { id: 7, skillname : "Bootstrap", imageUrl: "/skills/bootstrap.svg" },
    { id: 19, skillname: "Docker", imageUrl: "/skills/docker.svg" },
    { id: 22, skillname: "Firebase", imageUrl: "/skills/firebase.svg" },
    { id: 26, skillname: "Git", imageUrl: "/skills/git.svg" },
    { id: 27, skillname: "Go", imageUrl: "/skills/go.svg" },
    { id: 28, skillname: "GraphQL", imageUrl: "/skills/graphql.svg" },
    { id: 38, skillname: "Markdown", imageUrl: "/skills/markdown.svg" },
    { id: 44, skillname: "MySQL", imageUrl: "/skills/mysql.svg" },
    { id: 45, skillname: "Next.js", imageUrl: "/skills/nextJS.svg" },
    { id: 46, skillname: "Nginx", imageUrl: "/skills/nginx.svg" },
    { id: 53, skillname: "PostgreSQL", imageUrl: "/skills/postgresql.svg" },
    { id: 61, skillname: "Strapi", imageUrl: "/skills/strapi.svg" },
    { id: 63, skillname: "Swift", imageUrl: "/skills/swift.svg" },
    { id: 68, skillname: "Vite", imageUrl: "/skills/vitejs.svg" },
    { id: 70, skillname: "Netlify", imageUrl: "/skills/vuetifyjs.svg" },

];
